### PR TITLE
Login Modal and NavBar Functions

### PR DESCRIPTION
**Pull request by jsnorek**
This pull request sets up the LoginModal.jsx and allows the user to enter their username and password to login. 

**Commits Summary**

- CSS updated to show Login Modal correctly
- "Cancel" Button closes Login Modal on click
- User input is compared to database information and if there is a match, the user data is pulled from database and user is "logged in" - a console.log confirms the correct data
- On login, NavBar shows "Profile", "MyShelf", and "Log In" button
- "Profile" and "MyShelf" button uses routes to open new pages (that are still in process but have placeholder text to show they work correctly)
- "Log Out" button clears login information 

**Next Steps**

- Still need to set up the "New User" button to function properly
- Populate Profile and MyShelf

### CODE REVIEW

**Comment by jsnorek** [comment]
@ismith @marjanasarker Can you take a look at this and let me know your thoughts?

**Comment by jsnorek** [comment]
@nianokia Hi! Can you take a look at this when you have some time?

**Review by marjanasarker — COMMENTED** [review]
for each of the main files, can you add a description of what the file is doing in your app for eg for LoginModal.jsx on line 1 of the file add something like  `** Components for login functionality of application. */`
this will help for documentation purposes

**Comment by nianokia** [comment]
# Review

## From my end, here are the features that worked, and I was able to test:
- CSS updated to show Login Modal correctly
     - It opened on desktop, so the modal didn't display very well. Once I realized you were prioritizing mobile then I saw 
        that the CSS displayed correctly.
- "Cancel" Button closes Login Modal on click
     - Works properly!
Screenshot 2024-10-18 at 11 47 25 AM


## Features that I wasn't able to test:
- User input is compared to database information and if there is a match, the user data is pulled from database and user is "logged in" - a console.log confirms the correct data
     - Since I would be a new user, I wasn't able to test the comparison and didn't see a console.log
- On login, NavBar shows "Profile", "MyShelf", and "Log In" button
     - I couldn't log in, so I was unable to see any of the login features like the NavBar showing up.
- "Profile" and "MyShelf" button uses routes to open new pages (that are still in process but have placeholder text to show they work correctly)
     - I also couldn't test the routes since I was unable to login 
- "Log Out" button clears login information
     - I couldn't test logging out since I couldn't log in.
     
login demo

## Suggestions:
- Add a db dump maybe, so others can test the database comparison

**Comment by jsnorek** [comment]
@nianokia great feedback! I've added a db dump :)

**Comment by jsnorek** [comment]
@marjanasarker I've added the additional comments for each component! Thanks!

**Pull request merged**
